### ISSUE TITLE
Resize observer CSS missing

### ISSUE THREAD

**Issue by sisou** [Akryum/vue-virtual-scroller#372]
You removed the inclusion of the resize-observer CSS in `build/rollup.config.base.js` lines 24-25. This now has the effect that the resize observer is no longer positioned absolute in the scroller, but instead at the bottom, creating a margin at the bottom and failing to detect resizes. 

https://github.com/Akryum/vue-virtual-scroller/commit/db85e92530c187fc0de350cf64ed880b20868e73#diff-b9e51815a1d433112da1024aff629b69L24-L25

**Comment by sisou** [comment]
Fixed in 1.0.4, awesome, thanks! :+1:

**Comment by gbaggaley** [comment]
This issue is back again in the latest release.

My `build/rollup.config.base.js` is:
```js
import babel from 'rollup-plugin-babel'
import resolve from 'rollup-plugin-node-resolve'
import cjs from 'rollup-plugin-commonjs'
import replace from 'rollup-plugin-replace'

const config = require('../package.json')

export default {
	input: 'src/index.js',
	plugins: [
		resolve({
			jsnext: true,
			main: true,
			browser: true,
		}),
		babel({
			exclude: 'node_modules/**',
			runtimeHelpers: true,
		}),
		cjs(),
		replace({
			VERSION: JSON.stringify(config.version),
		}),
	],
	watch: {
		include: 'src/**',
	},
}
```
